### ISSUE TITLE
Higher NPC are displayed as NPC 1_ETC_01 ID:46

### ISSUE THREAD

**Issue by zeiragna** [vthibault/roBrowser#105]
![issues](https://cloud.githubusercontent.com/assets/9783326/5061492/f8b915ac-6dd3-11e4-8055-4b0c7c556beb.png)

actual NPC ID was 4_F_FENRIR ID: 664

Client on left, browser on right.

**Comment by Ancyker** [comment]
JT_4_F_IU = 646,
      JT_4_M_RAGI = 647,
      JT_4_M_MELODY = 648,
      JT_4_TRACE = 649,
      JT_4_F_HIMEL = 650,
      JT_4_LEVITATEMAN = 651,
      JT_4_M_HEINRICH = 652,
      JT_4_M_ROYALGUARD = 653,
      JT_4_M_BARMUND = 654,
      JT_4_F_KHALITZBURG = 655,
      JT_4_F_HIMEL2 = 656,
      JT_4_WHITEKNIGHT = 657,
      JT_4_COCO = 658,
      JT_4_M_ALADDIN = 659,
      JT_4_M_GENIE = 660,
      JT_4_F_GENIE = 661,
      JT_4_JP_MID_SWIM = 662,
      JT_4_JP_RUNE_SWIM = 663,
      JT_4_F_FENRIR = 664,
      JT_4_F_GEFFEN_FAY = 665,
      JT_4_F_IRIS = 666,
      JT_4_F_LUCILE = 667,
      JT_4_F_SARAH_BABY = 668,
      JT_4_GEFFEN_01 = 669,
      JT_4_GEFFEN_02 = 670,
      JT_4_GEFFEN_03 = 671,
      JT_4_GEFFEN_04 = 672,
      JT_4_GEFFEN_05 = 673,
      JT_4_GEFFEN_06 = 674,
      JT_4_GEFFEN_07 = 675,
      JT_4_GEFFEN_08 = 676,
      JT_4_GEFFEN_09 = 677,
      JT_4_GEFFEN_10 = 678,
      JT_4_GEFFEN_11 = 679,
      JT_4_GEFFEN_12 = 680,
      JT_4_GEFFEN_13 = 681,
      JT_4_GEFFEN_14 = 682,
      JT_4_M_CHAOS = 683,
      JT_4_M_CHIEF_IRIN = 684,
      JT_4_M_SAKRAY = 685,
      JT_4_M_SAKRAYROYAL = 686,
      JT_4_TOWER_01 = 687,
      JT_4_TOWER_02 = 688,
      JT_4_TOWER_03 = 689,
      JT_4_TOWER_04 = 690,
      JT_4_TOWER_05 = 691,
      JT_4_TOWER_06 = 692,
      JT_4_TOWER_07 = 693,
      JT_4_TOWER_08 = 694,
      JT_4_TOWER_09 = 695,
      JT_4_TOWER_10 = 696,
      JT_4_TOWER_11 = 697,
      JT_4_TOWER_12 = 698,
      JT_4_TOWER_13 = 699,

**Comment by vthibault** [comment]
Thanks @Ancyker, got it on my local version, going to push it once I'm on a computer.
