### ISSUE TITLE
A very-long job name at Character Select window, Character Overview window, missing 3D animation for few skills and more

### ISSUE THREAD

**Issue by Konard** [vthibault/roBrowser#109]
Extended Super Novice is too big to fit in field width and overlaps next field value.

![2015-01-26 02-02-46](https://cloud.githubusercontent.com/assets/1431904/5893709/93c11506-a4ff-11e4-89da-cc885e7e4be7.png)

This job name does not fit in Character Overview window.

![2015-01-26 02-17-59](https://cloud.githubusercontent.com/assets/1431904/5893768/cdc31c70-a501-11e4-9ad6-c8a02a4580a4.png)

May be these fields and windows should be wider?

Also strange behaviour has an Novice Guard - I cannot equip it. All other items are ok.

There is no 3D animation for skills: Blessing, Increase Agility, Decrease Agility, Heal, Fire Bolt, Cold Bolt, Soul Strike, Sight, Napalm Beat, Safety Wall, Frost Driver, Fire Ball, Ruwach, Hiding, Envenom, Detoxify, Fire Pillar, Jupitel Thunder, Ice Wall, Frost Nova, Earth Spike, Heaven's Drive, First Aid, Call Spirits, Absorb Spirits, Magic Crasher (and may be others).

Something is wrong with Water Ball.

Skill Monster Property does not have visualization at all.

![2015-01-26 02-43-28](https://cloud.githubusercontent.com/assets/1431904/5893855/2d5fb1cc-a505-11e4-993c-49a4d7ef3faf.png)

**Comment by MStr3am** [comment]
About the name - why not just call the character name => Ex Super Novice

**Comment by Konard** [comment]
"ex-president - a former president ex-president" same here "former super novice"? Ex is not usually associated with extended. May be short name is a good idea, but not the "ex".

**Comment by balrogsamson** [comment]
Why not just keep it as "Super Novice"? Users and players will know the difference between the extended and non- anyway. Is that how RO does it? However, we could always just use Ext. Super Novice, right?
