### ISSUE TITLE
Uncaught TypeError: Cannot read property 'queryUsageAndQuota' of undefined

### ISSUE THREAD

**Issue by anacondaqq** [vthibault/roBrowser#110]
In all browser without changes after latest updates robrowser died... 
In console we recieve this error

> Uncaught TypeError: Cannot read property 'queryUsageAndQuota' of undefined

Browser Version: 40.0.2214.93

**Comment by herenow** [comment]
After some investigation it seems like we are trying to access what is now considered part of the DOM, `navigator.webkitTemporaryStorage` is no longer available in the worker context, which is where files are loaded in roBrowser.

I think we should move `queryUsageAndQuota` to the main thread, and post a message to the worker thread with this data.

I'll issue a pull request with a fix, and wait for KeyWorld.
