### ISSUE TITLE
Uncaught TypeError: Cannot read property 'queryUsageAndQuota' of undefined

### ISSUE THREAD

**Issue by Akkarinage** [vthibault/roBrowser#112]
I've just updated to 14796c95dbf70b6124c962346e8407cf590e90f1 and now receive the above error in my Chrome console. I have rebuilt all JS files and I'm not running in Development mode.

The error is referencing ThreadEventHandler.js:83

**Comment by anacondaqq** [comment]
same here

**Comment by herenow** [comment]
Is seems to be working here.

Did you guys recompile the Thread build?

`queryUsageAndQuota` should not be referenced in the new ThreadEventHandler build, since we moved it away from it.

**Comment by anacondaqq** [comment]
@herenow done. Working fine with last update.
