### ISSUE TITLE
Loading over SSL does not work

### ISSUE THREAD

**Issue by Ancyker** [vthibault/roBrowser#116]
When opening the client on https it tries to load elements over http, which fails due to the security restrictions.

**Comment by anacondaqq** [comment]
{
listen 80;
server_name "yourdomain.com"
return 301 https://yourdomain.com$request_uri;
}
(nginx example)

+ rewrite all http files from http to https at your web-server.
For me it's works fine.

**Comment by herenow** [comment]
Is your `ROConfig.remoteClient` set to a `https` url?

It should load assets from a `https` server if it's setup correctly.
