### ISSUE TITLE
New packets (Hercules)

### ISSUE THREAD

**Issue by Ancyker** [vthibault/roBrowser#127]
https://github.com/HerculesWS/Hercules/commit/eb0d0dc6

This change broke roBrowser. Characters, monsters and NPC's no longer show. It's possible other things are affected as well. Our packetver is 20140212.

Character server:
````
[Network] Packet "0x8b9" not register, skipping 10 bytes.
````

Map server:
````
[Network] Packet "0x9dd" not register, skipping 4979 bytes.
[Network] Packet "0x0" not register, skipping 4352 bytes.
[Network] Packet "0x9db" not register, skipping 93 bytes.
[Network] Packet "0x9dc" not register, skipping 144 bytes.
````

Also seeing:
````
Uncaught TypeError: Cannot read property 'isAdmin' of null
````

**Comment by vthibault** [comment]
I did some work on https://github.com/vthibault/roBrowser/tree/bugfix/127
I'll try to test it tomorrow before merging as I need to setup a new server for it.

Feel free to test it too if you want,
Anyway, thanks for the report :)
