### ISSUE TITLE
Hello, Demo page doesn't work now.

### ISSUE THREAD

**Issue by jhs512** [vthibault/roBrowser#129]
Hello Demo page ( http://demo.robrowser.com/?demo/2.5/ ) doesn't work now.

the error messag is : fail to connect to server

on Windows 10, Chorme Latest Ver

-----------------------------------------------------------------------

i found the demo server status on main page.

do you have any plans for running demo server?

**Comment by vthibault** [comment]
Sometime it crashes for some reasons, it's a small server and do not like when people abusing GMs commands to spam a lot of monsters :)

It's up !
