### ISSUE TITLE
Files from GRFs not being extracted into data

### ISSUE THREAD

**Issue by DevKiddo** [vthibault/roBrowser#138]
Bonjour Vincent,

I hate bugging developers about their projects but I've been trying to get this to work for a week and my brain is about to explode. I tried registering in your forum to submit this issue but I'm not getting the confirmation email for some reason (searched my spam folder as well). The issue I have is the same one described in the following posts:

* http://forum.robrowser.com/index.php?topic=32269.0
* https://github.com/vthibault/roBrowser/issues/86

I've found numerous other posts describing the same or a similar issue and have tried to debug my issue with the solutions provided by yourself or the community. But in short, several files that exist within my data.grf aren't being extracted into the data folder so when the browser looks for them, they're not there and I get 404s.

Checklist:
- php is being loaded
- AllowOverride All for the robrowser directory is enabled
- All .htaccess files are being read perfectly, I've tested this by writing some nonsense in them.
- rewrite module has also been enabled
- index.php in debug mode says everything is fine and all grfs are loaded
- the ErrorDocument path should be correct as I am only getting normal 404s and not 404s mentioning ErrorDocument

If I manually extract the files into the data folder, robrowser works like a charm so for some reason files aren't being extracted out of the grfs but client/index.php doesn't say anything bad is going on.

This is the url in case you want to check the html file: http://88.21.156.28:90/robrowser/index.html

I'm not sure if this would be a problem but I'm using port 90. Also, the robrowser folder in my web document directory is a symlink to the actual robrowser folder in an sdcard.

Jimmy

**Comment by javierlog08** [comment]
Im not sure about what is the problem you have right now.

Can't you run ro-browser or do you have a problem with the GRF module ?

Share a screen of you chrome console anyway

Regards !

**Comment by DevKiddo** [comment]
Hi Javier, 

Thanks for getting back to me so fast! I can run robrowser but all I get is a black screen because some files aren't being loaded. I put the address of the server where i'm hosting robrowser in my original post: http://88.21.156.28:90/robrowser/index.html

Please open the url in your browser and check out the debugging console for yourself! it'll be more efficient than sending you screenshots :P

**Comment by javierlog08** [comment]
In the RO API config, set the value debug, to true.
That should works

**Comment by DevKiddo** [comment]
done, now what?

**Comment by javierlog08** [comment]
No bro, you are wrong...change the API file like this

                                function initialize() {
                                        var ROConfig = {
                                                target:        document.getElementById("robrowser"),
                                                type:          ROBrowser.TYPE.FRAME,
                                                application:   ROBrowser.APP.ONLINE,
                                                remoteClient:  "http://88.21.156.28:90/robrowser/client/",
                                                packetver:     20151104,
                                                disableKorean: true,
                                                width: 800,
						height: 600,
						version: 1.0,
                                                skipIntro: true,
                                                skipServerList: true,
                                                **development: true, // CHANGE THIS TO TRUE**
                                                socketProxy: 'ws://88.21.156.28:5999/', 
                                                servers: 'data/clientinfo.xml'
                                        };
                                        var RO = new ROBrowser(ROConfig);
                                        RO.start();
                                }
                                window.addEventListener("load", initialize, false);
                        

And then set your client in php to debug: false

**Comment by DevKiddo** [comment]
Hi Javier, I changed the html file before. Perhaps your cache has the older index.html? I just turned the client in php to debug: false. Please let me know how to proceed!

**Comment by javierlog08** [comment]
Its seems that is a problem from the remote client.
Be sure you have correctly the DATA.ini file in the resource file in the remote-client side.

**Comment by DevKiddo** [comment]
I do! It's just a DATA.ini file containing the following content:

```
[Data]
0=eddyro_pal.grf
1=dresspack.grf
2=rdata.grf
3=data.grf
```

**Comment by DevKiddo** [comment]
Working now. I had to repack the grfs with decrypt on. For some reason the index.php debugger never told me that it couldnt decrypt the grf files though. Now I'm troubleshooting through the fact that I get disconnected upon selecting my character, but hopefully I can get that done myself
